[package]
name = "dplayr"
version = "0.2.0"
authors = ["dastrukar <3derid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
